### ISSUE TITLE
access.xml deny to Default and Guest users

### ISSUE THREAD

**Issue by zorrigas** [quiret/resedit#1]
Can't deny access to Defaults and Guest accounts, any user (logged or not) can open editor and download scripts.

**Comment by quiret** [comment]
Hi! I will look at your issue next weekend. Unfortunatly I was preoccupied.

I can tell you this much: by editing acl.xml of your MTA server you can restrict resource access to moderators only. Simply put all your protected resources into a special ACL group that only you can edit. Also make sure to use serverside command "resedit_accupd" if you want to reload "access.xml" when editing it (otherwise resedit will overwrite with old version on restart).

Next time I will make a tutorial video, do not worry.

**Comment by zorrigas** [comment]
Any update?

**Comment by quiret** [comment]
https://youtu.be/UCqR9SqC4BQ

Does this help? :)
